services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container-chapi
    environment:
      MYSQL_ROOT_PASSWORD: verysecure
      MYSQL_DATABASE: chapi
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    container_name: mailpit-chapi
    restart: unless-stopped
    volumes:
      - mailpit-data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
    mariadb-data:
    mailpit-data:
